const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';

const ERROR = 'ERROR';
const NO_ERROR = 'NO_ERROR';

const CONTACTS = 'CONTACTS';
const ADD_CONTACT = 'ADD_CONTACT';
const EDIT_CONTACT = 'EDIT_CONTACT';
const DELETE_CONTACT = 'DELETE_CONTACT';
const REDIRECT = 'REDIRECT';
const SEARCH_CONTACT = 'SEARCH_CONTACT';


export {
    LOGIN,
    LOGOUT,
    ERROR,
    NO_ERROR,
    CONTACTS,
    ADD_CONTACT,
    EDIT_CONTACT,
    DELETE_CONTACT,
    REDIRECT
}